# Simple code 

In [1]:
import numpy as np

# ============================================================
# STEP 1 : DATA
# ============================================================

X = np.array([
    [2, 4],
    [4, 8],
    [6, 12]
], dtype=float)

print("Original Data:\n", X)


# ============================================================
# STEP 2 : MEAN CENTERING
# ============================================================

mean = np.mean(X, axis=0)
X_centered = X - mean

print("\nMean:\n", mean)
print("\nCentered Data:\n", X_centered)


# ============================================================
# STEP 3 : COVARIANCE MATRIX
# ============================================================

cov_matrix = np.cov(X_centered, rowvar=False)

print("\nCovariance Matrix:\n", cov_matrix)


# ============================================================
# STEP 4 : EIGEN VALUES & EIGEN VECTORS
# ============================================================

eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

print("\nEigen Values:\n", eigen_values)
print("\nEigen Vectors:\n", eigen_vectors)


# ============================================================
# STEP 5 : SORT EIGEN VALUES
# ============================================================

sorted_index = np.argsort(eigen_values)[::-1]

sorted_eigenvalues = eigen_values[sorted_index]
sorted_eigenvectors = eigen_vectors[:, sorted_index]

print("\nSorted Eigen Values:\n", sorted_eigenvalues)
print("\nSorted Eigen Vectors:\n", sorted_eigenvectors)


# ============================================================
# STEP 6 : SELECT TOP K EIGENVECTORS
# ============================================================

k = 1

principal_components = sorted_eigenvectors[:, :k]

print("\nPrincipal Components:\n", principal_components)


# ============================================================
# STEP 7 : TRANSFORM DATA
# ============================================================

X_pca = np.dot(X_centered, principal_components)

print("\nReduced Data:\n", X_pca)

Original Data:
 [[ 2.  4.]
 [ 4.  8.]
 [ 6. 12.]]

Mean:
 [4. 8.]

Centered Data:
 [[-2. -4.]
 [ 0.  0.]
 [ 2.  4.]]

Covariance Matrix:
 [[ 4.  8.]
 [ 8. 16.]]

Eigen Values:
 [ 0. 20.]

Eigen Vectors:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]

Sorted Eigen Values:
 [20.  0.]

Sorted Eigen Vectors:
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

Principal Components:
 [[-0.4472136 ]
 [-0.89442719]]

Reduced Data:
 [[ 4.47213595]
 [ 0.        ]
 [-4.47213595]]


# sklearn implmentation

In [2]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# ============================================================
# STEP 1 : DATA
# ============================================================

X = np.array([
    [2, 4],
    [4, 8],
    [6, 12]
], dtype=float)

print("Original Data:\n", X)


# ============================================================
# STEP 2 : STANDARDIZATION
# ============================================================

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("\nScaled Data:\n", X_scaled)


# ============================================================
# STEP 3 : APPLY PCA
# ============================================================

pca = PCA(n_components=1)

X_pca = pca.fit_transform(X_scaled)


# ============================================================
# RESULTS
# ============================================================

print("\nReduced Data:\n", X_pca)
print("\nPrincipal Components:\n", pca.components_)
print("\nExplained Variance:\n", pca.explained_variance_)
print("\nExplained Variance Ratio:\n", pca.explained_variance_ratio_)

Original Data:
 [[ 2.  4.]
 [ 4.  8.]
 [ 6. 12.]]

Scaled Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

Reduced Data:
 [[-1.73205081]
 [ 0.        ]
 [ 1.73205081]]

Principal Components:
 [[0.70710678 0.70710678]]

Explained Variance:
 [3.]

Explained Variance Ratio:
 [1.]


# Scratch

In [3]:
class PCAScratch:

    def __init__(self, n_components=1):
        self.n_components = n_components

    def fit(self, X):

        # Mean centering
        self.mean = X.mean(axis=0)
        X_centered = X - self.mean

        # Covariance matrix
        cov = np.cov(X_centered, rowvar=False)

        # Eigenvalues and eigenvectors
        eigenvalues, eigenvectors = np.linalg.eigh(cov)

        # Sort descending
        idx = np.argsort(eigenvalues)[::-1]

        eigenvalues = eigenvalues[idx]
        eigenvectors = eigenvectors[:, idx]

        self.components = eigenvectors[:, :self.n_components]

        self.explained_variance = (
            eigenvalues[:self.n_components]
            / eigenvalues.sum()
        )

    def transform(self, X):

        X_centered = X - self.mean

        return X_centered @ self.components


pca = PCAScratch(n_components=1)

pca.fit(X)

X_reduced = pca.transform(X)

print(X_reduced)
print("Explained Variance:",
      pca.explained_variance)

[[-2.82842712]
 [-1.41421356]
 [ 0.        ]
 [ 1.41421356]
 [ 2.82842712]]
Explained Variance: [1.]


## Important Formulas

### 1. Mean

$$
\mu = \frac{1}{n}\sum_{i=1}^{n} x_i
$$

### 2. Mean Centering

$$
X_c = X - \mu
$$

### 3. Covariance Matrix

$$
C = \frac{1}{n-1}X_c^T X_c
$$

### 4. Eigenvalue Equation

$$
Cv = \lambda v
$$

### 5. Projection

$$
Z = X_c W
$$