# 1. Dataset

In [1]:
import numpy as np

# -------------------- Input Image --------------------

image = np.array([
    [1,2,3,0,1],
    [4,5,6,1,2],
    [7,8,9,2,3],
    [1,2,3,4,5],
    [6,7,8,9,0]
], dtype=float)

# Image Shape = (5,5)

kernel = np.array([
    [1,0],
    [0,-1]
], dtype=float)

# Kernel Shape = (2,2)

print("Image Shape :", image.shape)
print("Kernel Shape:", kernel.shape)

Image Shape : (5, 5)
Kernel Shape: (2, 2)


# 2. Tensorflow

In [2]:
import tensorflow as tf

image_tf = image.reshape(1,5,5,1)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(
        filters=1,
        kernel_size=(2,2),
        activation="relu",
        input_shape=(5,5,1)
    ),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2))
])

output = model.predict(image_tf)

print(output)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
[[[[0.8717935]
   [5.563142 ]]

  [[1.0862744]
   [5.159443 ]]]]


# 3. Custom CNN

In [3]:
import numpy as np

class CNN:

    def convolution(self, image, kernel):

        h, w = image.shape
        kh, kw = kernel.shape

        out_h = h - kh + 1
        out_w = w - kw + 1

        output = np.zeros((out_h, out_w))

        for i in range(out_h):

            for j in range(out_w):

                region = image[i:i+kh, j:j+kw]

                output[i, j] = np.sum(region * kernel)

        return output


    def max_pooling(self, feature_map, size=2):

        h, w = feature_map.shape

        out_h = h // size
        out_w = w // size

        output = np.zeros((out_h, out_w))

        for i in range(out_h):

            for j in range(out_w):

                region = feature_map[
                    i*size:(i+1)*size,
                    j*size:(j+1)*size
                ]

                output[i, j] = np.max(region)

        return output


cnn = CNN()

feature_map = cnn.convolution(image, kernel)

print("Feature Map")
print(feature_map)

pooled = cnn.max_pooling(feature_map)

print("\nPooled Output")
print(pooled)

Feature Map
[[-4. -4.  2. -2.]
 [-4. -4.  4. -2.]
 [ 5.  5.  5. -3.]
 [-6. -6. -6.  4.]]

Pooled Output
[[-4.  4.]
 [ 5.  5.]]


# 4. CNN (From Scratch)

## Convolution

A kernel slides over the image.

$$
Output(i,j)
=
\sum
Image
\times
Kernel
$$

Code

```python
region = image[i:i+kh, j:j+kw]

output[i,j] = np.sum(region * kernel)
```

---

## Feature Map

The output after applying convolution is called the Feature Map.

---

## Max Pooling

Max pooling reduces spatial dimensions.

$$
Output(i,j)
=
\max(region)
$$

Code

```python
output[i,j]=np.max(region)
```

---

## Shapes

| Variable | Shape |
|-----------|-------|
| Image | $(H,W)$ |
| Kernel | $(K,K)$ |
| Feature Map | $(H-K+1,W-K+1)$ |
| Pool Output | $(H/2,W/2)$ |